// angular-app/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import {
  provideFASTDesignSystem,
  fastTextField,
} from '@microsoft/fast-components';
import { badge, label, provideMODDesignSystem, textInput } from 'design-system';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

provideFASTDesignSystem().register(fastTextField());

provideMODDesignSystem()
  .register(badge())
  .register(label())
  .register(textInput());

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));

// design-system-react/src/index.ts
import { provideReactWrapper } from "@microsoft/fast-react-wrapper";
import React from "react";

import { badge, label, textInput, provideMODDesignSystem } from "design-system";

const { wrap } = provideReactWrapper(
  React,
  provideMODDesignSystem().register(label())
);

export const MODBadge = wrap(badge());
export const MODTextInput = wrap(textInput());
